Add email subscription form component
pingcap/website-docs pull request #474
Opened 2024-03-15 04:30 UTC by likidu

@lilin90 @Yuiham 

Email subscription form component for #453 

In markdown file, add `<EmailSubscriptionForm />` to where we want to enable the email subscription such as the [release-notes.md](https://github.com/pingcap/docs/blob/87aff487d536847304737feaacaa49b12b006982/releases/release-notes.md#L4)

2024-05-21 09:59 UTC, Yuiham commented on src/components/MDXComponents/email-subscription-form.module.css
In the `website-docs` project, we use `CSS-in-JS` instead of CSS Module. So we can remove this file.

2024-05-21 09:59 UTC, Yuiham commented on src/components/MDXComponents/email-subscription-form.module.css.d.ts
This file is unnecessary.

2024-05-21 09:59 UTC, Yuiham commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +            </p>
```suggestion
            <Box component="p" color={(theme) => theme.status.error}>
              {formData.error === "invalidEmail" ? (
                <Trans i18nKey="releaseSubscription.error.invalidEmail" />
              ) : (
                <Trans i18nKey="releaseSubscription.error.networkError" />
              )}
            </Box>
```

2024-05-22 02:56 UTC, Yuiham commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +        });
We can use `axios` instead.

```suggestion
import axios from "axios";

        await axios.post(API_URL, undefined, {
          email: formData.email
        });
```

2024-05-22 03:15 UTC, Yuiham commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +              </Button>
Prefer
```suggestion
import { LoadingButton } from "@mui/lab"

              <LoadingButton
                type="submit"
                variant="contained"
                color="primary"
                loading={formData.loading}
                loadingIndicator={t('releaseSubscription.button.subscribing')}
                sx={{ marginLeft: "1rem" }}
              >
                <Trans i18nKey="releaseSubscription.button.subscribe" />
              </LoadingButton>
```

2024-05-22 03:15 UTC, Yuiham commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +              />
Prefer
```suggestion
              <TextField
                size="small"
                variant="outlined"
                type="text"
                name="email"
                placeholder={t("releaseSubscription.placeholder")}
                value={formData.email}
                onChange={handleChange}
                error={!!formData.error}
                helperText={formData.error === "invalidEmail" ? t('releaseSubscription.error.invalidEmail') : t('releaseSubscription.error.networkError')}
              />
```

And then we can remove the following error message block.

2024-05-22 03:35 UTC, Yuiham reviewed
@likidu PTAL these comments. Thx!

2024-05-22 03:35 UTC, Yuiham commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +export function EmailSubscriptionForm() {
As the release note subscription feature is disabled in the JA docs, we need to wrap `EmailSubscriptionForm` for rendering in different languages.

```suggestion
export function EmailSubscriptionWrapper() {
  const { language } = useI18next();
  const disabled = language === Locale.ja;
  
  if (disabled) {
  	return null;
  }
  
  return <EmailSubscriptionForm />
}

// Collect email address that subscribe to TiDB release and send it to the SendGrid API
function EmailSubscriptionForm() {
```

2024-05-22 03:38 UTC, shhdgit reviewed
the rest LGTM.

2024-05-22 03:38 UTC, shhdgit commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +      console.log("Email is valid");
```suggestion
```

2024-05-22 03:38 UTC, shhdgit commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +        console.log("Email subscription form submitted");
```suggestion
```

2024-05-22 06:19 UTC, Yuiham commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +          )}
If we use the `error` prop and the `helperText` prop of `TextField`, we can remove this block.

2024-05-22 06:21 UTC, Yuiham commented on src/components/MDXComponents/index.tsx
> +export { EmailSubscriptionForm } from "components/MDXComponents/EmailSubscriptionForm";
```suggestion
export { EmailSubscriptionWrapper } from "components/MDXComponents/EmailSubscriptionForm";
```

2024-05-22 06:53 UTC, Yuiham requested changes
@likidu PTAL again, thx!

2024-05-22 06:53 UTC, Yuiham commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +            </Box>
I made a mistake. The correct codes are:

```suggestion
            <Box display="flex" alignItems="baseline">
              <TextField
                size="small"
                variant="outlined"
                type="text"
                name="email"
                placeholder={t("releaseSubscription.placeholder")}
                value={formData.email}
                onChange={handleChange}
                error={!!formData.error}
                helperText={!!formData.error ? (formData.error === "invalidEmail" ? t('releaseSubscription.error.invalidEmail') : t('releaseSubscription.error.networkError')) : ' '}
              />

              <LoadingButton
                type="submit"
                variant="contained"
                color="primary"
                loading={formData.loading}
                loadingIndicator={t('releaseSubscription.button.subscribing')}
                ml="1rem"
              >
                <Trans i18nKey="releaseSubscription.button.subscribe" />
              </LoadingButton>
            </Box>
```

2024-05-22 07:25 UTC, Yuiham commented on src/components/MDXComponents/EmailSubscriptionForm.tsx
> +        });
```suggestion
        const payload = new URLSearchParams({
          email: formData.email
        })
        await axios.post(API_URL, payload);
```

2024-05-22 08:47 UTC, Yuiham approved these changes

2024-05-22 09:26 UTC, merged